AllCops:
  Exclude:
    - '*.md'
    - 'Gemfile'
    - 'Gemfile.lock'
    - db/schema.rb
    - config/**/*.rb
    - script/rails

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Metrics/LineLength:
  Max: 130
  Exclude:
    - '*.gemspec'

Style/RescueModifier:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/tmp/**/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*.rb'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'